/* EasyLEDMap: exporters. Pure functions: project in, list of files out. */
(function (root) {
  'use strict';
  const node = (typeof require !== 'undefined' && typeof module !== 'undefined');
  const M = node ? require('./model.js') : root.LM.model;
  const VERSION = '0.1.0';

  const safe = s => String(s || '').replace(/[^\w\- .]+/g, '_').trim() || 'led_map';
  const cid = s => String(s || '').replace(/[^A-Za-z0-9]+/g, '_').replace(/^_+|_+$/g, '') || 'x';
  function cArray(type, name, values, opts) {
    const o = Object.assign({ perLine: 16, progmem: true, size: '' }, opts);
    const lines = [];
    for (let i = 0; i < values.length; i += o.perLine) lines.push('  ' + values.slice(i, i + o.perLine).join(', '));
    return `const ${type} ${name}[${o.size}]${o.progmem ? ' PROGMEM' : ''} = {\n${lines.join(',\n')}\n};\n`;
  }
  const fmt = (v, type) => type === 'float' ? (Number.isInteger(v) ? v.toFixed(1) : String(v)) + 'f' : String(v);
  function stamp(project) { return `Generated by EasyLEDMap ${VERSION} from "${project.name}"`; }

  /** Median spacing between neighbouring live LEDs on the same strip, in world units. */
  function medianPitch(leds) {
    const d = [];
    for (let i = 1; i < leds.length; i++) {
      const a = leds[i - 1], b = leds[i];
      if (a.strip === b.strip) d.push(Math.hypot(b.x - a.x, b.y - a.y));
    }
    d.sort((x, y) => x - y);
    return d.length ? d[d.length >> 1] : 1;
  }

  /** Snap live LEDs onto a grid for matrix style maps. Returns { w, h, cells (index or -1), dropped }. */
  function gridMap(res, width, maxSide) {
    const live = res.leds.filter(l => !l.dead);
    if (!live.length) return { w: 1, h: 1, cells: [-1], dropped: 0 };
    let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;
    for (const l of live) { minX = Math.min(minX, l.x); maxX = Math.max(maxX, l.x); minY = Math.min(minY, l.y); maxY = Math.max(maxY, l.y); }
    const W = Math.max(maxX - minX, 1e-9), H = Math.max(maxY - minY, 1e-9);
    let w = width > 1 ? width : Math.round(W / medianPitch(live)) + 1;
    maxSide = maxSide || 255;
    let cell = W / Math.max(1, w - 1), h = Math.round(H / cell) + 1;
    if (w > maxSide || h > maxSide) { const k = Math.max(w, h) / maxSide; w = Math.max(1, Math.floor(w / k)); cell = W / Math.max(1, w - 1); h = Math.min(maxSide, Math.round(H / cell) + 1); }
    const cells = new Array(w * h).fill(-1); let dropped = 0;
    for (const l of live) {
      const gx = (l.x - minX) / cell, gy = (l.y - minY) / cell;
      let best = -1, bd = Infinity;
      for (let dy = -1; dy <= 1; dy++) for (let dx = -1; dx <= 1; dx++) {
        const cx = Math.round(gx) + dx, cy = Math.round(gy) + dy;
        if (cx < 0 || cy < 0 || cx >= w || cy >= h || cells[cy * w + cx] !== -1) continue;
        const dd = (cx - gx) ** 2 + (cy - gy) ** 2; if (dd < bd) { bd = dd; best = cy * w + cx; }
      }
      if (best < 0) dropped++; else cells[best] = l.index;
    }
    return { w, h, cells, dropped };
  }

  /** Group ranges over an ordering. order[k] = LED index at position k. */
  function groupTables(project, res, posOf) {
    const out = [];
    project.groups.forEach((g, gi) => {
      const ids = new Set(g.leds);
      const members = res.leds.filter(l => ids.has(l.id) && !l.dead);
      const pos = members.map(l => posOf[l.index]).filter(p => p >= 0).sort((a, b) => a - b);
      const contiguous = pos.length > 0 && pos[pos.length - 1] - pos[0] === pos.length - 1;
      let sx = 0, sy = 0; for (const l of members) { sx += l.x; sy += l.y; }
      out.push({ gi, name: g.name, count: pos.length, pos, contiguous, start: pos.length ? pos[0] : 0, cx: members.length ? sx / members.length : 0, cy: members.length ? sy / members.length : 0, members });
    });
    return out;
  }

  /* ------------------------------------------------------------------ WLED */
  function wled(project) {
    const o = project.exports.wled, s = project.setup, res = M.resolve(project), warnings = [], files = [];
    const chip = M.CHIPSETS[s.chipset] || M.CHIPSETS.OTHER;
    const live = res.leds.filter(l => !l.dead);
    // Virtual order: the pixels effects will see, in the order they will see them.
    let virt;
    if (o.order === 'groups' && project.groups.length) {
      const placed = new Set(); virt = [];
      for (const g of project.groups) {
        const ids = new Set(g.leds);
        for (const l of live) if (ids.has(l.id) && !placed.has(l.index)) { placed.add(l.index); virt.push(l.index); }
      }
      for (const l of live) if (!placed.has(l.index)) virt.push(l.index);
    } else virt = live.map(l => l.index);
    const posOf = new Array(res.total).fill(-1); virt.forEach((p, k) => { posOf[p] = k; });
    // Pad to the full physical length with -1 so dead pixels are unmapped on every WLED version.
    const map = virt.concat(new Array(res.total - virt.length).fill(-1));
    files.push({ name: 'ledmap.json', text: `{"n":${JSON.stringify(project.name)},"map":[${map.join(',')}]}\n` });
    if (res.total > 1800) warnings.push(`This map has ${res.total} entries. WLED 0.15 loads the whole file into a fixed JSON buffer, so maps much beyond about 1,800 entries may fail to load on 0.15.x.`);

    const gt = groupTables(project, res, posOf);
    const nonContig = gt.filter(g => g.count && !g.contiguous);
    if (nonContig.length) warnings.push(`${nonContig.length} group(s) are not one unbroken run in this pixel order (${nonContig.slice(0, 4).map(g => g.name).join(', ')}${nonContig.length > 4 ? ', …' : ''}). Switch pixel order to "Packed by group" to make every group a single range.`);
    const multi = res.leds.filter(l => l.groups.length > 1).length;
    if (multi) warnings.push(`${multi} LED(s) belong to more than one group. LM_GROUP_OF records only the first.`);

    const norm = M.normalise(res.leds, { origin: o.origin, yUp: o.yUp, keepAspect: o.keepAspect, lo: M.INT_TYPES[o.coordType].lo, hi: M.INT_TYPES[o.coordType].hi, includeDeadInBounds: o.includeDeadInBounds });
    const T = M.INT_TYPES[o.coordType].c, big = project.groups.length > 254, GT = big ? 'uint16_t' : 'uint8_t', none = big ? 65535 : 255;
    const centroid = (g, axis) => {
      if (!g.members.length) return 0;
      let a = 0; for (const l of g.members) a += axis === 'x' ? norm.x[l.index] : norm.y[l.index];
      return M.castValue(a / g.members.length, o.coordType);
    };
    let h = `// ${stamp(project)}\n// Header for WLED custom effects and usermods. Indexes are the mapped (virtual) pixel\n// indexes that effects see once ledmap.json is loaded. Dead pixels are not in the map.\n#pragma once\n#include <stdint.h>\n#ifndef PROGMEM\n#define PROGMEM\n#endif\n\n`;
    h += `#define LM_NUM_PHYSICAL ${res.total}   // LEDs on the wire, dead pixels included\n#define LM_NUM_PIXELS   ${virt.length}   // mapped pixels (set the segment to 0..${virt.length})\n#define LM_NUM_GROUPS   ${gt.length}\n#define LM_NO_GROUP     ${none}\n\n`;
    if (gt.length) {
      h += `// Group g covers mapped pixels LM_GROUP_START[g] .. LM_GROUP_START[g] + LM_GROUP_LEN[g] - 1.\n// A length of 0 means the group is not one unbroken run; use LM_GROUP_OF for those.\n`;
      h += gt.map((g, i) => `//  ${String(i).padStart(3)}  ${g.name}  (${g.count} px)${g.count && !g.contiguous ? '  NOT CONTIGUOUS' : ''}`).join('\n') + '\n';
      h += cArray('uint16_t', 'LM_GROUP_START', gt.map(g => g.contiguous ? g.start : 0), { size: 'LM_NUM_GROUPS' });
      h += cArray('uint16_t', 'LM_GROUP_LEN', gt.map(g => g.contiguous ? g.count : 0), { size: 'LM_NUM_GROUPS' });
      h += `// Centre of each group, ${T} ${o.coordType === 'float' ? '' : `${M.INT_TYPES[o.coordType].lo}..${M.INT_TYPES[o.coordType].hi}`}, ${o.yUp ? 'Y up' : 'Y down'}.\n`;
      h += cArray(T, 'LM_GROUP_X', gt.map(g => fmt(centroid(g, 'x'), o.coordType)), { size: 'LM_NUM_GROUPS' });
      h += cArray(T, 'LM_GROUP_Y', gt.map(g => fmt(centroid(g, 'y'), o.coordType)), { size: 'LM_NUM_GROUPS' });
      h += `// Group of each mapped pixel, or LM_NO_GROUP.\n`;
      h += cArray(GT, 'LM_GROUP_OF', virt.map(p => res.leds[p].groups.length ? res.leds[p].groups[0] : none), { size: 'LM_NUM_PIXELS', perLine: 24 });
    }
    h += `// Position of each mapped pixel.\n`;
    h += cArray(T, 'LM_X', virt.map(p => fmt(M.castValue(norm.x[p], o.coordType), o.coordType)), { size: 'LM_NUM_PIXELS' });
    h += cArray(T, 'LM_Y', virt.map(p => fmt(M.castValue(norm.y[p], o.coordType), o.coordType)), { size: 'LM_NUM_PIXELS' });
    files.push({ name: 'led_map_wled.h', text: h });

    if (gt.length) files.push({
      name: 'lm_group_effect_example.h', text:
`// ${stamp(project)}
// Example custom effect: every group lights as one pixel.
// Written against the WLED 0.15.x effect API. Not compiled or run on hardware by the tool:
// treat it as a starting point. It assumes one segment covering mapped pixels 0..LM_NUM_PIXELS.
#include "led_map_wled.h"

static uint16_t mode_lm_groups(void) {
  for (uint16_t g = 0; g < LM_NUM_GROUPS; g++) {
    uint8_t hue = (uint8_t)((g * 255U) / LM_NUM_GROUPS + (strip.now >> 5));
    uint32_t c = SEGMENT.color_from_palette(hue, false, true, 0);
    uint16_t start = pgm_read_word(&LM_GROUP_START[g]);
    uint16_t len = pgm_read_word(&LM_GROUP_LEN[g]);
    for (uint16_t i = 0; i < len; i++) SEGMENT.setPixelColor(start + i, c);
  }
  return FRAMETIME;
}
static const char _data_FX_MODE_LM_GROUPS[] PROGMEM = "Group Pixels@!;;!";

// Register it from a usermod's setup():
//   strip.addEffect(255, &mode_lm_groups, _data_FX_MODE_LM_GROUPS);
` });

    if (o.grid) {
      const g = gridMap(res, +o.gridWidth || 0, 128);
      files.push({ name: 'ledmap_2d.json', text: `{"n":${JSON.stringify(project.name + ' 2D')},"width":${g.w},"height":${g.h},"map":[${g.cells.join(',')}]}\n` });
      if (g.dropped) warnings.push(`2D map: ${g.dropped} LED(s) landed on a cell that was already taken and were left out. Use a wider grid.`);
    }

    // Setup sheet
    const P = M.power(project);
    const wiring = o.order !== 'groups' || !project.groups.length;
    let segs = null;
    if (wiring) { let a = 0; segs = res.strips.map((st, i) => { const seg = { id: i, start: a, stop: a + st.live, n: st.name }; a += st.live; return seg; }).filter(x => x.stop > x.start); }
    let t = `# WLED setup for ${project.name}\n\n${stamp(project)}\n\n`;
    t += `## LED outputs (Config > LED Preferences)\n\n| Output | Name | GPIO | Type | Colour order | Length |\n|---|---|---|---|---|---|\n`;
    res.strips.forEach((st, i) => { t += `| ${i + 1} | ${st.name} | ${st.pin} | ${chip.wled} | ${s.colorOrder} | ${st.count} |\n`; });
    t += `\nTotal LEDs: ${res.total} (${res.live} mapped, ${res.total - res.live} dead).\nLengths include dead pixels: they are still on the data line.\n\n`;
    t += `## Current\n\n- LED voltage: ${s.voltage} V\n- Per pixel at full white: ${s.maPerPixel} mA (set this as the per-LED current in WLED)\n- Mapped pixels at full white: ${P.ampsLive.toFixed(2)} A (${P.wattsLive.toFixed(0)} W)\n- Suggested WLED maximum current: ${P.wledLimitMa} mA${+s.psuAmps > 0 ? ` (90% of your ${s.psuAmps} A supply)` : ' (enter your supply size in Setup to base this on the supply)'}\n\nThese are estimates from the numbers in Setup, not measurements.\n\n`;
    t += `## Load the map\n\n1. Open http://<controller>/edit and upload ledmap.json.\n2. Reboot, or pick the map under Config > 2D/LED map if your build shows that menu.\n3. Set the main segment to start 0, stop ${virt.length}. Everything past ${virt.length} is a dead pixel and stays dark because the map leaves it unmapped.\n\n`;
    t += `The map is padded with -1 to the full length (${res.total}). WLED 0.15.x lets pixels past the end of a short map light up directly, and the padding prevents that.\n\n`;
    if (segs && segs.length > 1) t += `## One segment per strip (optional)\n\nPOST this to http://<controller>/json/state:\n\n\`\`\`json\n${JSON.stringify({ seg: segs })}\n\`\`\`\n\n`;
    if (gt.length) t += `## Groups\n\n${gt.length} groups are in led_map_wled.h as start and length tables. Stock WLED has no setting that makes ${gt.length} unequal groups each behave as one pixel (segments are capped at 32 on a standard ESP32, and segment grouping only handles equal sizes), so group effects need a custom effect or usermod that reads that header. lm_group_effect_example.h is a starting point.\n\n`;
    t += `## Before you flash custom firmware\n\nNote the firmware version and build name shown under Info, and keep a USB recovery path. Some controllers need a board-specific build.\n`;
    files.push({ name: 'wled_setup.md', text: t });
    return { files, warnings, summary: { total: res.total, live: virt.length, groups: gt.length } };
  }

  /* --------------------------------------------------------------- FastLED */
  function fastled(project) {
    const o = project.exports.fastled, s = project.setup, res = M.resolve(project), warnings = [], files = [];
    const chip = M.CHIPSETS[s.chipset] || M.CHIPSETS.OTHER, P = M.power(project);
    const T = M.INT_TYPES[o.coordType], lo = o.coordType === 'float' ? +o.lo : Math.max(T.lo, +o.lo), hi = o.coordType === 'float' ? +o.hi : Math.min(T.hi, +o.hi);
    const norm = M.normalise(res.leds, { origin: o.origin, yUp: o.yUp, keepAspect: o.keepAspect, lo, hi, includeDeadInBounds: o.includeDeadInBounds });
    const posOf = res.leds.map(l => l.dead ? -1 : l.index);
    const gt = groupTables(project, res, posOf);
    const big = project.groups.length > 254, GT = big ? 'uint16_t' : 'uint8_t', none = big ? 65535 : 255;
    const rd = o.coordType === 'float' ? 'pgm_read_float' : (o.coordType.endsWith('16') ? 'pgm_read_word' : 'pgm_read_byte');
    let h = `// ${stamp(project)}\n// Arrays are in data order: entry i belongs to leds[i].\n#pragma once\n#include <FastLED.h>\n\n`;
    h += `#define LM_NUM_LEDS      ${res.total}\n#define LM_NUM_LIVE      ${res.live}\n#define LM_NUM_STRIPS    ${res.strips.length}\n#define LM_NUM_GROUPS    ${gt.length}\n#define LM_NO_GROUP      ${none}\n#define LM_LED_TYPE      ${chip.fastled}\n#define LM_COLOR_ORDER   ${s.colorOrder.slice(0, 3)}\n#define LM_VOLTS         ${s.voltage}\n#define LM_MAX_MILLIAMPS ${P.wledLimitMa}\n\n`;
    h += `// Strip ${'#'}: data pin, first index, length\n` + res.strips.map((st, i) => `//  ${i}: GPIO ${st.pin}, ${st.start}, ${st.count}  ${st.name}`).join('\n') + '\n';
    h += cArray('uint8_t', 'LM_STRIP_PIN', res.strips.map(st => st.pin), { size: 'LM_NUM_STRIPS', progmem: false });
    h += cArray('uint16_t', 'LM_STRIP_START', res.strips.map(st => st.start), { size: 'LM_NUM_STRIPS', progmem: false });
    h += cArray('uint16_t', 'LM_STRIP_COUNT', res.strips.map(st => st.count), { size: 'LM_NUM_STRIPS', progmem: false });
    h += `\n// Position of each LED: ${T.c}, range ${lo}..${hi}, origin ${o.origin === 'center' ? 'centre' : (o.yUp ? 'bottom left' : 'top left')}, ${o.yUp ? 'Y up' : 'Y down'}${o.keepAspect ? ', aspect ratio kept' : ', stretched to fill'}.\n`;
    h += cArray(T.c, 'LM_X', Array.from(norm.x, v => fmt(M.castValue(v, o.coordType), o.coordType)), { size: 'LM_NUM_LEDS' });
    h += cArray(T.c, 'LM_Y', Array.from(norm.y, v => fmt(M.castValue(v, o.coordType), o.coordType)), { size: 'LM_NUM_LEDS' });
    h += `inline ${T.c} lmX(uint16_t i) { return (${T.c})${rd}(&LM_X[i]); }\ninline ${T.c} lmY(uint16_t i) { return (${T.c})${rd}(&LM_Y[i]); }\n\n`;
    h += `// Group of each LED, or LM_NO_GROUP. Dead pixels have no group.\n`;
    h += cArray(GT, 'LM_GROUP', res.leds.map(l => (!l.dead && l.groups.length) ? l.groups[0] : none), { size: 'LM_NUM_LEDS', perLine: 24 });
    h += `inline ${GT} lmGroup(uint16_t i) { return (${GT})${big ? 'pgm_read_word' : 'pgm_read_byte'}(&LM_GROUP[i]); }\n\n`;
    const bits = new Array(Math.ceil(res.total / 8) || 1).fill(0);
    res.leds.forEach(l => { if (l.dead) bits[l.index >> 3] |= 1 << (l.index & 7); });
    h += `// One bit per LED, set when the pixel is dead (on the data line but kept dark).\n`;
    h += cArray('uint8_t', 'LM_DEAD_BITS', bits.map(b => '0x' + b.toString(16).padStart(2, '0')), { perLine: 20 });
    h += `inline bool lmIsDead(uint16_t i) { return (pgm_read_byte(&LM_DEAD_BITS[i >> 3]) >> (i & 7)) & 1; }\n\n`;
    if (gt.length) {
      h += `// Groups. A length of 0 means the group is not one unbroken run of indexes; use LM_GROUP for those.\n` + gt.map((g, i) => `//  ${String(i).padStart(3)}  ${g.name}  (${g.count} px)`).join('\n') + '\n';
      h += cArray('uint16_t', 'LM_GROUP_START', gt.map(g => g.contiguous ? g.start : 0), { size: 'LM_NUM_GROUPS' });
      h += cArray('uint16_t', 'LM_GROUP_LEN', gt.map(g => g.contiguous ? g.count : 0), { size: 'LM_NUM_GROUPS' });
    }
    if (o.grid) {
      const g = gridMap(res, +o.gridWidth || 0, 255);
      h += `\n// Grid lookup. Cells with no LED return LM_NUM_LEDS, so declare CRGB leds[LM_NUM_LEDS + 1].\n#define LM_GRID_W ${g.w}\n#define LM_GRID_H ${g.h}\n`;
      h += cArray('uint16_t', 'LM_GRID', g.cells.map(c => c < 0 ? res.total : c), { size: 'LM_GRID_W * LM_GRID_H' });
      h += `inline uint16_t XY(uint8_t x, uint8_t y) {\n  if (x >= LM_GRID_W || y >= LM_GRID_H) return LM_NUM_LEDS;\n  return pgm_read_word(&LM_GRID[(uint16_t)y * LM_GRID_W + x]);\n}\n`;
      if (g.dropped) warnings.push(`Grid lookup: ${g.dropped} LED(s) landed on a cell that was already taken and are not reachable through XY(). Use a wider grid.`);
    }
    files.push({ name: 'led_map.h', text: h });

    let ino = `// ${stamp(project)}\n// Example sketch. Not compiled or run on hardware by the tool: treat it as a starting point.\n#include <FastLED.h>\n#include "led_map.h"\n\nCRGB leds[LM_NUM_LEDS + 1];   // +1 is a spare pixel for off-grid writes\n\nvoid setup() {\n`;
    res.strips.forEach(st => { ino += `  FastLED.addLeds<LM_LED_TYPE, ${st.pin}, LM_COLOR_ORDER>(leds, ${st.start}, ${st.count});   // ${st.name}\n`; });
    ino += `  FastLED.setMaxPowerInVoltsAndMilliamps(LM_VOLTS, LM_MAX_MILLIAMPS);\n}\n\nvoid loop() {\n  uint8_t t = millis() >> 4;\n  for (uint16_t i = 0; i < LM_NUM_LEDS; i++) {\n    if (lmIsDead(i)) { leds[i] = CRGB::Black; continue; }\n`;
    ino += gt.length ? `    ${GT} g = lmGroup(i);\n    if (g == LM_NO_GROUP) leds[i] = CRGB::Black;\n    else leds[i] = CHSV((uint8_t)(g * 255 / LM_NUM_GROUPS) + t, 255, 255);   // one colour per group\n` : `    leds[i] = CHSV((uint8_t)(lmX(i) >> ${o.coordType.endsWith('16') ? 8 : 0}) + t, 255, 255);   // sweep along X\n`;
    ino += `  }\n  FastLED.show();\n}\n`;
    if (o.coordType === 'float' && !gt.length) ino = ino.replace(/\(uint8_t\)\(lmX\(i\) >> 0\)/, '(uint8_t)(lmX(i) * 255)');
    files.push({ name: 'led_map_example.ino', text: ino });
    return { files, warnings, summary: { total: res.total, live: res.live, groups: gt.length } };
  }

  /* --------------------------------------------------------- TouchDesigner */
  function crc32(buf) {
    let t = crc32.t;
    if (!t) { t = crc32.t = new Uint32Array(256); for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1; t[n] = c >>> 0; } }
    let c = 0xFFFFFFFF; for (let i = 0; i < buf.length; i++) c = t[(c ^ buf[i]) & 0xFF] ^ (c >>> 8);
    return (c ^ 0xFFFFFFFF) >>> 0;
  }
  /** 16 bit RGB PNG, one row. Uses stored deflate blocks so it needs no compressor. */
  function png16(width, height, rgb16) {
    const row = 1 + width * 6, raw = new Uint8Array(row * height);
    for (let y = 0; y < height; y++) {
      raw[y * row] = 0;
      for (let x = 0; x < width * 3; x++) { const v = rgb16[y * width * 3 + x]; raw[y * row + 1 + x * 2] = v >> 8; raw[y * row + 2 + x * 2] = v & 255; }
    }
    const blocks = Math.ceil(raw.length / 65535) || 1, z = new Uint8Array(2 + raw.length + blocks * 5 + 4);
    let p = 0; z[p++] = 0x78; z[p++] = 0x01;
    for (let b = 0; b < blocks; b++) {
      const s = b * 65535, len = Math.min(65535, raw.length - s);
      z[p++] = b === blocks - 1 ? 1 : 0; z[p++] = len & 255; z[p++] = len >> 8; z[p++] = ~len & 255; z[p++] = (~len >> 8) & 255;
      z.set(raw.subarray(s, s + len), p); p += len;
    }
    let a = 1, bsum = 0; for (let i = 0; i < raw.length; i++) { a = (a + raw[i]) % 65521; bsum = (bsum + a) % 65521; }
    z[p++] = bsum >> 8; z[p++] = bsum & 255; z[p++] = a >> 8; z[p++] = a & 255;
    const chunk = (type, data) => {
      const out = new Uint8Array(12 + data.length), dv = new DataView(out.buffer);
      dv.setUint32(0, data.length); for (let i = 0; i < 4; i++) out[4 + i] = type.charCodeAt(i);
      out.set(data, 8); dv.setUint32(8 + data.length, crc32(out.subarray(4, 8 + data.length))); return out;
    };
    const ihdr = new Uint8Array(13), dv = new DataView(ihdr.buffer);
    dv.setUint32(0, width); dv.setUint32(4, height); ihdr[8] = 16; ihdr[9] = 2;
    const parts = [new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]), chunk('IHDR', ihdr), chunk('IDAT', z), chunk('IEND', new Uint8Array(0))];
    const out = new Uint8Array(parts.reduce((n, x) => n + x.length, 0)); let q = 0; for (const x of parts) { out.set(x, q); q += x.length; }
    return out;
  }

  function touchdesigner(project) {
    const o = project.exports.td, s = project.setup, res = M.resolve(project), warnings = [], files = [];
    const chip = M.CHIPSETS[s.chipset] || M.CHIPSETS.OTHER, ch = chip.white ? 4 : 3;
    const norm = M.normalise(res.leds, { origin: o.origin, yUp: o.yUp, keepAspect: o.keepAspect, lo: +o.lo, hi: +o.hi, includeDeadInBounds: o.includeDeadInBounds });
    const uv = M.normalise(res.leds, { origin: 'corner', yUp: true, keepAspect: false, lo: 0, hi: 1, includeDeadInBounds: o.includeDeadInBounds });
    const perU = Math.max(1, Math.min(Math.floor(512 / ch), +o.universeSize || Math.floor(512 / ch)));
    const r5 = v => (Math.round(v * 1e5) / 1e5).toString();
    const q = v => /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v;
    let csv = 'index,strip,strip_name,pin,strip_index,x,y,u,v,dead,group,group_name,universe,channel\n';
    let uni = +o.firstUniverse || 0, inU = 0, lastStrip = -1;
    for (const l of res.leds) {
      if (o.stripsStartUniverse && l.strip !== lastStrip && lastStrip !== -1 && inU > 0) { uni++; inU = 0; }
      if (inU >= perU) { uni++; inU = 0; }
      lastStrip = l.strip;
      const g = l.groups.length ? l.groups[0] : -1;
      csv += [l.index, l.strip, q(res.strips[l.strip].name), res.strips[l.strip].pin, l.stripIndex, r5(norm.x[l.index]), r5(norm.y[l.index]), r5(uv.u[l.index]), r5(uv.v[l.index]), l.dead ? 1 : 0, g, g < 0 ? '' : q(project.groups[g].name), uni, inU * ch + 1].join(',') + '\n';
      inU++;
    }
    files.push({ name: 'led_map.csv', text: csv });
    const gt = groupTables(project, res, res.leds.map(l => l.dead ? -1 : l.index));
    if (gt.length) {
      let g = 'group,name,count,x,y,u,v\n';
      for (const t of gt) {
        let x = 0, y = 0, u = 0, v = 0; for (const l of t.members) { x += norm.x[l.index]; y += norm.y[l.index]; u += uv.u[l.index]; v += uv.v[l.index]; }
        const n = t.members.length || 1;
        g += [t.gi, q(t.name), t.count, r5(x / n), r5(y / n), r5(u / n), r5(v / n)].join(',') + '\n';
      }
      files.push({ name: 'led_groups.csv', text: g });
    }
    // UV lookup texture: pixel i holds (u, v) of LED i in red and green. Blue is 65535 for live, 0 for dead.
    if (res.total > 0) {
      const tex = new Uint16Array(res.total * 3);
      res.leds.forEach(l => { const c = t => Math.max(0, Math.min(65535, Math.round(t * 65535))); tex[l.index * 3] = c(uv.u[l.index]); tex[l.index * 3 + 1] = c(uv.v[l.index]); tex[l.index * 3 + 2] = l.dead ? 0 : 65535; });
      files.push({ name: 'led_uv_16bit.png', bytes: png16(res.total, 1, tex) });
    }
    const lastU = uni;
    files.push({
      name: 'touchdesigner_notes.md', text:
`# TouchDesigner files for ${project.name}

${stamp(project)}

- led_map.csv: one row per LED in data order. x and y are in ${o.lo}..${o.hi} (${o.origin === 'center' ? 'origin at the centre' : 'origin at a corner'}, ${o.yUp ? 'Y up' : 'Y down'}${o.keepAspect ? ', aspect ratio kept' : ''}). u and v are 0..1 with the origin at the bottom left, the way TOPs address pixels.
- led_groups.csv: one row per group with its centre.
- led_uv_16bit.png: ${res.total} x 1 pixels. Red is u, green is v, blue is 1 for live pixels and 0 for dead ones. Feed it to the second input of a Remap TOP to sample your content at every LED, then convert the result with a TOP to CHOP.
- Layout aspect ratio (width / height): ${norm.aspect.toFixed(4)}. Build your content at this aspect so u and v land where the LEDs are.

## Output

Universe and channel columns assume ${ch} channels per pixel and ${perU} pixels per universe${o.stripsStartUniverse ? ', with each strip starting on a new universe' : ''}. Universes ${+o.firstUniverse || 0} to ${lastU} are used. Channel is the 1-based DMX address of the first colour channel. If you send DDP to WLED you can ignore both columns and send the pixels in index order.
` });
    files.push({ name: 'led_layout.png', render: 'layout' });
    return { files, warnings, summary: { total: res.total, live: res.live, groups: gt.length, universes: lastU - (+o.firstUniverse || 0) + 1 } };
  }

  const api = { wled, fastled, touchdesigner, gridMap, groupTables, png16, crc32, safe, VERSION };
  if (node) module.exports = api;
  root.LM = root.LM || {}; root.LM.exporters = api;
})(typeof self !== 'undefined' ? self : globalThis);
